# Generated by Django 5.2 on 2025-12-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0003_place_lat_place_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
