# Generated by Django 5.2 on 2025-12-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_alter_placeimage_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="description_long",
            new_name="long_description",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="description_short",
            new_name="short_description",
        ),
    ]
