# Generated by Django 5.2 on 2025-12-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0010_rename_description_long_place_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
    ]
